# Generated by Django 4.2.7 on 2023-11-04 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('survey', '0002_delete_answer_delete_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('neis', models.CharField(max_length=4)),
                ('career', models.IntegerField()),
                ('department', models.IntegerField()),
                ('year', models.IntegerField()),
                ('subject', models.IntegerField()),
            ],
        ),
    ]
