# Generated by Django 4.2.7 on 2023-11-04 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='survey',
            name='career',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='department',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='neis',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='year',
        ),
    ]
